export enum EventTypes {
  NETWORK_CONNECTED,
  NETWORK_DISCONNECTED,
  NETWORK_RECONNECTING,

  READY,
  HELLO,
  DISPATCH,
  HEARTBEAT,
  HEARTBEAT_ACK,

  GUILD_CREATE,
  GUILD_DELETE,
  GUILD_UPDATE,
  GUILD_POSITION,

  CHANNEL_CREATE,
  CHANNEL_DELETE,
  CHANNEL_UPDATE,
  CHANNEL_POSITION,

  GUILD_ROLE_CREATE,
  GUILD_ROLE_DELETE,
  GUILD_ROLE_UPDATE,
  GUILD_ROLE_POSITION,

  GUILD_MEMBER_ADD,
  GUILD_MEMBER_REMOVE,
  GUILD_MEMBER_UPDATE,

  EMOJI_CREATE,
  EMOJI_DELETE,
  EMOJI_UPDATE,

  MESSAGE_CREATE,
  MESSAGE_DELETE,
  MESSAGE_UPDATE,

  MESSAGE_REACTION_ADD,
  MESSAGE_REACTION_REMOVE,

  USER_TYPING,
  USER_PRESENCE_UPDATE,

  VOICE_STATE_UPDATE,
}

type ET = keyof typeof EventTypes;

export default ET;
